const allWorkouts = [
  /* Cardio */ [
    { name: "Jumping Jacks",
      img1:"./img/JumpingJack1.png",
      img2:"./img/JumpingJack2.png",
      img3:"./img/JumpingJack1.png",
      img4:"./img/JumpingJack2.png",
    },
    { name: "High Knees",
      img1:"./img/HighKnees1.png",
      img2:"./img/HighKnees2.png",
      img3:"./img/HighKnees1.png",
      img4:"./img/HighKnees2.png",
    },
    { name: "Butt Kicks",
      img1:"./img/ButtKick1.png",
      img2:"./img/ButtKick2.png",
      img3:"./img/ButtKick1.png",
      img4:"./img/ButtKick2.png",
    },
  ],
  /* Upper/Lower Body */ [
    { name: "Wall Sit",
      img1:"./img/WallSit.png",
      img2:"./img/WallSit.png",
      img3:"./img/WallSit.png",
      img4:"./img/WallSit.png",
    },
    { name: "Push Ups",
      img1:"./img/PushUp1.png",
      img2:"./img/PushUp2.png",
      img3:"./img/PushUp1.png",
      img4:"./img/PushUp2.png",
    },
    { name: "Squats",
      img1:"./img/JumpingJack1.png",
      img2:"./img/Squat.png",
      img3:"./img/JumpingJack1.png",
      img4:"./img/Squat.png",
    },
  ],
  /* Core */ [
    { name: "Sit Ups",
      img1:"./img/SitUp1.png",
      img2:"./img/SitUp2.png",
      img3:"./img/SitUp1.png",
      img4:"./img/SitUp2.png",
    },
    { name: "Plank",
      img1:"./img/Plank.png",
      img2:"./img/Plank.png",
      img3:"./img/Plank.png",
      img4:"./img/Plank.png",
    },
    { name: "The Bridge",
      img1:"./img/Bridge.png",
      img2:"./img/Bridge.png",
      img3:"./img/Bridge.png",
      img4:"./img/Bridge.png",
    },
  ],
];
